# Generated by Django 5.1.6 on 2025-03-03 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_administrativestaff_healthcareprovider_patient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='service_description',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Invoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_amount', models.FloatField()),
                ('Insurance_percent_cover', models.FloatField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], default='pending', max_length=20)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.patient')),
                ('prescription_service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.prescription')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.healthcareprovider')),
            ],
        ),
    ]
