# Generated by Django 5.1.6 on 2025-03-03 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_prescription_service_description_invoices'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoices',
            old_name='prescription_service',
            new_name='prescription',
        ),
    ]
