# Generated by Django 5.1.6 on 2025-03-03 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_prescription_service_invoices_prescription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoices',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='invoices',
            name='provider',
        ),
    ]
