# Generated by Django 5.1.6 on 2025-03-04 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_invoices_prescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='send',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together={('provider', 'date', 'time')},
        ),
    ]
