# Generated by Django 5.1.6 on 2025-03-05 22:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_prescription_send_alter_appointment_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoices',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
