# Generated by Django 5.2b1 on 2025-03-06 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_invoices_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoices',
            name='Insurance_percent_cover',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='invoices',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
